name: home_services
description: home_services customer app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  # package ame
  change_app_package_name: ^1.0.0
  # GET
  get: 4.6.1
  get_storage: 2.1.1
  # DIO
  dio: 4.0.4
  dio_http_cache: 0.3.0
  # FONT
  google_fonts: 2.2.0
  #IMAGES, SLIDERS, LAYOUTS
  cached_network_image: 3.2.0
  carousel_slider: 4.0.0
#  flutter_svg: 0.22.0
#  flutter_svg: 2.0.5
  flutter_staggered_grid_view: 0.6.0
  image_picker: 0.8.4+4
  flutter_image_compress: ^1.1.3
  cupertino_icons: any
  shimmer: 2.0.0
  # WEB
  webview_flutter: 2.8.0
#  flutter_sslcommerz:
  fluttertoast:
#  flutter_html: 2.2.1
  flutter_html: 2.1.3
#  flutter_html_view: any
  url_launcher: 6.0.17
  # FIREBASE
#  firebase_messaging: 11.2.5
#  cloud_firestore: 3.1.6
#  firebase_auth: 3.3.5
#  firebase_core: 1.11.0
#  firebase_storage: 10.2.5

#  firebase_messaging: ^11.2.5
  cloud_firestore: 4.14.0 #^4.3.1
  firebase_auth: ^4.2.5
  firebase_core: 2.24.2 #2.4.1
  firebase_messaging:

  firebase_storage: ^11.0.10
  countdown: ^0.1.0
#  firebase_storage: ^11.2.6
  provider: ^6.1.1
  shared_preferences: ^2.0.6
#  googleapis_auth:
#  http:


  # GOOGLE MAPS
  google_maps_flutter:
  geocoding:

  place_picker: ^0.10.0
  #Local Database
  sqflite: ^2.0.2+1
  namefully: ^0.1.8+1
  internet_connection_checker: ^0.0.1+4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  #  flutter_pusher_client: ^0.3.1
  #  laravel_echo: ^0.2.8
  #  laravel_flutter_pusher: ^0.0.4

  pusher_channels_flutter: 2.2.1 #^1.0.5
  logger: ^1.1.0
  geolocator: ^9.0.2
#  fl_country_code_picker: ^0.0.4
#  flutter_local_notifications: ^13.0.0
  flutter_ringtone_player: ^3.2.0
  fan_carousel_image_slider: ^0.1.2




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons:



dependency_overrides:
  json_annotation: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - config/
    - assets/img/
    - assets/screens/
    - assets/icon/
    - assets/locales/

